export type StoryType =
  | "language_divergence"
  | "language_convergence"
  | "article_instability"
  | "under_radar"
  | "match_recap";

export type PublishedStory = {
  id: string;
  slug: string;
  type: StoryType;
  label: string;
  title: string;
  excerpt: string;
  match?: string;
  entity?: string;
  languages: string[];
  publishedAt: string;
  sourceCount: number;
  isDemo: boolean;
  heroImage?: string;
  comparison?: {
    language: string;
    shortLabel: string;
    observation: string;
    status: "present" | "absent" | "unstable";
  }[];
};

export type TrackedMatch = {
  id: string;
  slug?: string;
  teams: [string, string];
  stage: string;
  dateLabel: string;
  timeLabel: string;
  status: "upcoming" | "live" | "completed";
  trackedPagesLabel: string;
  isDemo: boolean;
};

export type ObservatoryTeaserType = {
  capturedEdits: number;
  monitoredLanguages: number;
  publishedStories: number;
  noiseFilteredPercent: number;
};

export type StoryLanguageState = {
  languageCode: "EN" | "ES" | "FR" | string;
  languageLabel: string;
  articleLabel: string;
  observedChange: string;
  translatedExcerpt?: string;
  sourceLabel: string;
  revisionTime: string;
  status: "present" | "absent" | "reworded" | "unstable";
};

export type StoryTimelineItem = {
  time: string;
  languageCode: string;
  title: string;
  description: string;
  kind: "match_event" | "addition" | "rewording" | "observation";
};

export type MatchPageState = "pre_match" | "live" | "post_match";

export type MatchTeam = {
  name: string;
  shortName: string;
  color: string;
};

export type MatchContext = {
  id: string;
  slug: string;
  state: MatchPageState;
  isDemo: boolean;
  demoLabel: string;
  competitionLabel: string;
  stageLabel: string;
  dateLabel: string;
  timeLabel: string;
  venueLabel: string;
  homeTeam: MatchTeam;
  awayTeam: MatchTeam;
  score?: [number, number];
  minute?: string;
  finalStatus?: string;
};

export type MatchTrackedSubject = {
  id: string;
  type: "match" | "team" | "player" | "coach" | "tournament";
  role?: "match" | "home_team" | "away_team" | "tournament";
  label: string;
  reason: string;
  languageCode?: string;
  pageTitle?: string;
  canonicalUrl?: string;
  wikiCode?: string;
};

export type MatchPublishedStory = {
  id: string;
  slug: string;
  type:
    | "fact_entry"
    | "language_convergence"
    | "language_divergence"
    | "article_instability"
    | "match_recap";
  categoryLabel: string;
  title: string;
  excerpt: string;
  languages: string[];
  timeLabel: string;
  statusLabel: string;
  isDemo: boolean;
  featured?: boolean;
};

export type MatchTimelineItem = {
  id: string;
  time: string;
  type: "match_event" | "wikipedia_observation" | "published_story";
  languageCode?: string;
  title: string;
  description: string;
  sourceStatus:
    | "official_event_demo"
    | "wikipedia_demo"
    | "published_demo"
    | "official_event"
    | "wikipedia_observation"
    | "published_story";
};

export type MatchLanguageComparison = {
  eventLabel: string;
  rows: {
    observation: string;
    EN: string;
    ES: string;
    FR: string;
  }[];
  conclusion: string;
  limitation: string;
};

export type ArticleInstabilityCase = {
  id: string;
  languageCode: string;
  articleLabel: string;
  sectionLabel: string;
  statusLabel: string;
  events: {
    time: string;
    action: "added" | "removed" | "restored" | "sourced";
    description: string;
  }[];
  observation: string;
  limitation: string;
};

export type MatchRecap = {
  title: string;
  summary: string;
  storyCount: number;
  comparedEditions: string[];
  stableFactsCount: number;
  instabilityCount: number;
  keyTakeaway: string;
};

export type StoryLanguageCode =
  | "EN"
  | "FR"
  | "ES"
  | "AR"
  | "JA"
  | "PT"
  | "DE"
  | "KO";

export type StoryArchiveItem = {
  id: string;
  slug: string;
  type: StoryType | "fact_entry";
  categoryLabel: string;
  // Level 2 rehearsal observations carry an explicit badge so the card can
  // signal that the public copy was generated by a template, not by an editor.
  badgeLabel?: string;
  title: string;
  excerpt: string;
  publishedAtLabel: string;
  matchLabel?: string;
  entityLabel?: string;
  languages: StoryLanguageCode[];
  sourceCount: number;
  readingTimeLabel: string;
  image?: string;
  isDemo: boolean;
  isFeatured?: boolean;
  availableDetailRoute?: string;
};

export type StoryArchiveFilter = {
  id: string;
  label: string;
  type?: StoryType | "fact_entry";
};

export type StoriesArchiveStats = {
  storyCount: number;
  matchCount: number;
  languageCount: number;
  sourceCount: number;
  isDemo: boolean;
};

export type FeaturedCollection = {
  id: string;
  label: string;
  title: string;
  description: string;
  storyIds: string[];
  isDemo: boolean;
};

export type MatchTrackingStatus =
  | "upcoming"
  | "observing"
  | "completed_with_stories"
  | "completed_without_story";

export type MatchStage =
  | "group_stage"
  | "round_of_32"
  | "round_of_16"
  | "quarter_final"
  | "semi_final"
  | "third_place"
  | "final";

export type MatchStoryType =
  | "fact_entry"
  | "language_convergence"
  | "language_divergence"
  | "article_instability"
  | "under_radar"
  | "match_recap";

export type TrackedMatchCard = {
  id: string;
  slug: string;
  dateLabel: string;
  timeLabel: string;
  stage: MatchStage;
  stageLabel: string;
  venueLabel?: string;
  homeTeam: MatchTeam;
  awayTeam: MatchTeam;
  status: MatchTrackingStatus;
  statusLabel: string;
  score?: [number, number];
  isDemo: boolean;
  monitoredSubjects: string[];
  storyCount?: number;
  languagesCompared?: string[];
  storyTypes?: MatchStoryType[];
  editorialSummary?: string;
  availableRoute?: string;
};

export type MatchDayGroup = {
  id: string;
  dateLabel: string;
  phaseLabel: string;
  matches: TrackedMatchCard[];
};

export type MatchesFilterState = {
  phase: "all" | MatchStage;
  status: "all" | MatchTrackingStatus | "completed_with_stories";
  teamQuery: string;
};

export type MatchesArchiveStats = {
  trackedMatches: number;
  dossiersPublished: number;
  upcomingMatches: number;
  comparedEditions: number;
  isDemo: boolean;
};

export type EntityType =
  | "player"
  | "team"
  | "coach"
  | "stadium"
  | "tournament";

export type EntityStoryType =
  | "fact_entry"
  | "language_convergence"
  | "language_divergence"
  | "article_instability"
  | "under_radar"
  | "match_recap";

export type EntityLanguageCode =
  | "JA"
  | "EN"
  | "FR"
  | "ES"
  | "AR"
  | "PT"
  | "DE"
  | "KO";

export type EntityProfile = {
  id: string;
  slug: string;
  type: EntityType;
  name: string;
  displayRole: string;
  associatedTeam: string;
  tournamentLabel: string;
  shortDescription: string;
  editorialAngle: string;
  isDemo: boolean;
  demoLabel: string;
  heroImage?: string;
};

export type EntityLanguageArticleState = {
  languageCode: EntityLanguageCode;
  languageLabel: string;
  articleLabel: string;
  articleDepthLabel: string;
  lastObservedLabel: string;
  substantiveChanges: number;
  presentClaims: string[];
  absentClaims: string[];
  translatedExcerpt?: string;
  sourceCount: number;
  state:
    | "expanded"
    | "limited"
    | "unchanged"
    | "unstable"
    | "not_observed";
};

export type EntityPublishedStory = {
  id: string;
  slug: string;
  type: EntityStoryType;
  categoryLabel: string;
  title: string;
  excerpt: string;
  dateLabel: string;
  languages: EntityLanguageCode[];
  matchLabel?: string;
  sourceCount: number;
  isDemo: boolean;
  availableRoute?: string;
};

export type EntityTimelineItem = {
  id: string;
  timeLabel: string;
  dateLabel: string;
  type:
    | "match_event"
    | "wikipedia_observation"
    | "published_story"
    | "comparison_snapshot";
  languageCode?: EntityLanguageCode;
  title: string;
  description: string;
  isDemo: boolean;
};

export type EntityRelatedMatch = {
  id: string;
  matchLabel: string;
  dateLabel: string;
  stageLabel: string;
  relationLabel: string;
  dossierStatus: "not_created" | "available" | "upcoming";
  isDemo: boolean;
};

export type EntityComparisonRow = {
  claimLabel: string;
  JA: string;
  EN: string;
  FR: string;
};

export type EntityComparisonCase = {
  categoryLabel: string;
  title: string;
  description: string;
  rows: EntityComparisonRow[];
  observation: string;
  limitation: string;
  isDemo: boolean;
};

export type ExplorerStoryType =
  | "fact_entry"
  | "language_convergence"
  | "language_divergence"
  | "article_instability"
  | "under_radar"
  | "match_recap";

export type ExplorerLanguageCode =
  | "EN"
  | "FR"
  | "ES"
  | "AR"
  | "JA"
  | "PT"
  | "DE"
  | "KO";

export type ExplorerViewMode =
  | "atlas"
  | "matrix"
  | "timeline";

export type StoryGeoAnchor = {
  id: string;
  storyId: string;
  subjectLabel: string;
  subjectType: "player" | "team" | "match" | "tournament";
  geographyLabel: string;
  latitude: number;
  longitude: number;
  type: ExplorerStoryType;
  title: string;
  excerpt: string;
  languages: ExplorerLanguageCode[];
  route?: string;
  isDemo: boolean;
};

export type ExplorerMatrixCellStatus =
  | "present"
  | "not_detected"
  | "unstable"
  | "not_compared"
  | "convergent";

export type ExplorerMatrixRow = {
  id: string;
  storyId: string;
  topicLabel: string;
  matchLabel?: string;
  type: ExplorerStoryType;
  languages: Record<ExplorerLanguageCode, {
    status: ExplorerMatrixCellStatus;
    shortText?: string;
  } | undefined>;
  conclusion: string;
  route?: string;
  isDemo: boolean;
};

export type ExplorerTimelineEvent = {
  id: string;
  dateLabel: string;
  order: number;
  type: ExplorerStoryType;
  categoryLabel: string;
  title: string;
  matchLabel?: string;
  languages: ExplorerLanguageCode[];
  route?: string;
  isDemo: boolean;
};

export type ExplorerLegendItem = {
  type: ExplorerStoryType;
  label: string;
  description: string;
  colorToken: string;
};

export type ExplorerStats = {
  publishedStories: number;
  mappedSubjects: number;
  comparedEditions: number;
  documentedMatches: number;
  isDemo: boolean;
};

export type ObservatoryChangeStatus =
  | "minor"
  | "substantive"
  | "linked_to_published_story";

export type ObservatoryChangeKind =
  | "formatting"
  | "result_added"
  | "incident_mention_added"
  | "sanction_added"
  | "performance_added"
  | "wording_removed"
  | "wording_restored"
  | "source_added"
  | "no_equivalent_detected";

export type ObservatoryLanguageCode =
  | "EN"
  | "FR"
  | "ES"
  | "JA"
  | "AR"
  | "PT";

export type ObservatoryArticleType =
  | "match"
  | "player"
  | "team"
  | "tournament";

export type ObservatoryTrace = {
  id: string;
  observedAtLabel: string;
  languageCode: ObservatoryLanguageCode;
  languageLabel: string;
  articleType: ObservatoryArticleType;
  articleLabel: string;
  entityLabel: string;
  matchLabel?: string;
  sectionLabel: string;
  changeKind: ObservatoryChangeKind;
  changeStatus: ObservatoryChangeStatus;
  statusLabel: string;
  summary: string;
  addedText?: string;
  removedText?: string;
  translatedText?: string;
  anonymizedContributorLabel: string;
  relatedStoryId?: string;
  relatedStoryTitle?: string;
  relatedStoryRoute?: string;
  isDemo: boolean;
};

export type ObservatoryTrackedArticle = {
  id: string;
  languageCode: ObservatoryLanguageCode;
  articleLabel: string;
  entityLabel: string;
  articleType: ObservatoryArticleType;
  monitoringReason: string;
  latestStatusLabel: string;
  relatedMatchLabel?: string;
  isDemo: boolean;
};

export type ObservatoryFilterState = {
  language: "all" | ObservatoryLanguageCode;
  status: "all" | ObservatoryChangeStatus;
  articleType: "all" | ObservatoryArticleType;
  match: "all" | string;
  searchQuery: string;
};

export type ObservatoryPublicStats = {
  observedTraces: number;
  substantialChanges: number;
  publishedStoryLinks: number;
  monitoredArticles: number;
  isDemo: boolean;
};

export type ObservatoryStorySourceChain = {
  storyId: string;
  storyTitle: string;
  storyRoute: string;
  categoryLabel: string;
  traceIds: string[];
  observation: string;
  limitation: string;
  isDemo: boolean;
};

export type ObservatoryPipelineStep = {
  id: string;
  label: string;
  publicDescription: string;
  publicStatus: "shown_here" | "published_elsewhere" | "private_later";
};

export type PublishedStoryDetail = {
  id: string;
  slug: string;
  type: "language_divergence";
  categoryLabel: string;
  title: string;
  subtitle: string;
  publishedAt: string;
  matchLabel: string;
  matchStage: string;
  eventLabel: string;
  languages: string[];
  isDemo: boolean;
  observedSummary: string;
  interpretationSummary: string;
  limitationSummary: string;
  languageStates: StoryLanguageState[];
  timeline: StoryTimelineItem[];
  relatedStoryIds: string[];
};

export type MethodologyHistoryType =
  | "fact_entry"
  | "language_convergence"
  | "language_divergence"
  | "article_instability"
  | "under_radar"
  | "match_recap";

export type MethodologyDefinition = {
  id: string;
  term: string;
  shortDefinition: string;
  fullDefinition: string;
  example?: string;
};

export type MethodologyPipelineStep = {
  id: string;
  number: string;
  label: string;
  title: string;
  description: string;
  visibleIn: "observatory" | "magazine" | "desk_private";
  statusLabel: string;
};

export type PublicationCriterion = {
  id: string;
  question: string;
  acceptedAnswer: string;
  rejectedExample: string;
};

export type MethodologyCaseStudy = {
  id: string;
  type: MethodologyHistoryType;
  categoryLabel: string;
  title: string;
  observation: string;
  interpretation: string;
  limitation: string;
  route?: string;
  isDemo: boolean;
};

export type MethodologyComparisonRule = {
  id: string;
  incorrectAssumption: string;
  correctReading: string;
};

export type MethodologyPrivacyPrinciple = {
  id: string;
  title: string;
  description: string;
  prohibitedPublicOutput: string[];
};

export type MethodologyAiRule = {
  id: string;
  task: string;
  allowed: boolean;
  explanation: string;
};

export type MethodologyLimitation = {
  id: string;
  title: string;
  description: string;
  consequence: string;
};

export type MethodologyFAQItem = {
  id: string;
  question: string;
  answer: string;
};

export type MethodologyVersionEntry = {
  version: string;
  dateLabel: string;
  status: string;
  changes: string[];
};

export type PublicSearchResultType =
  | "story"
  | "match"
  | "entity"
  | "public_trace"
  | "methodology";

export type SearchStoryCategory =
  | "fact_entry"
  | "language_convergence"
  | "language_divergence"
  | "article_instability"
  | "under_radar"
  | "match_recap";

export type SearchLanguageCode =
  | "EN"
  | "FR"
  | "ES"
  | "JA"
  | "AR"
  | "PT"
  | "DE"
  | "KO";

export type PublicSearchResult = {
  id: string;
  type: PublicSearchResultType;
  subtype?: SearchStoryCategory;
  title: string;
  excerpt: string;
  metadataLabel: string;
  languages?: SearchLanguageCode[];
  matchLabel?: string;
  entityLabel?: string;
  publicStatusLabel: string;
  keywords: string[];
  route?: string;
  available: boolean;
  isDemo: boolean;
};

export type SearchFilterType =
  | "all"
  | "story"
  | "match"
  | "entity"
  | "public_trace"
  | "methodology";

export type SearchSuggestion = {
  id: string;
  label: string;
  query: string;
  filter?: SearchFilterType;
  description: string;
};

export type SearchDemoStats = {
  indexedStories: number;
  indexedMatches: number;
  indexedSubjects: number;
  indexedPublicTraces: number;
  isDemo: boolean;
};

export type SearchPrivacyRule = {
  label: string;
  description: string;
};
